### ISSUE TITLE
Adapters to implement

### ISSUE THREAD

**Issue by jmartin84** [cohesivelabs/filesystem#4]
Dropbox
aws buckets
??

**Comment by CWSpear** [comment]
I think "AWS buckets" is referred to S3 normally.

We can look at what Flysystem supports, but I like GCS (Google Cloud Storage) personally and as I mentioned, memory (as well as local).

Flysystem has a bunch. I think local and S3 is enough to go public. I would prefer to add adapters as people need (and encourage people to write them) as opposed to maintaining everything.

**Comment by jmartin84** [comment]
I couldn't remember if s3 was right or something else - its been a long day :p

I guess its fair to not include dropbox out of the box because people don't really use it as a CDN in my experience

**Comment by jmartin84** [comment]
We should also discuss how to handle authentication

**Comment by CWSpear** [comment]
What do you mean? Each adapter would definitely have different constructor parameters. In S3's case, you pass in your AWS creds and a bucket name. We shouldn't need to handle auth.

**Comment by jmartin84** [comment]
I was thinking that it would be part of the core, but considering everything will be so different you're probably right in that it would be part of the adapter.

**Comment by CWSpear** [comment]
If you think of more adapters we want to add, open a new ticket, add the `requested adapter` and `task` labels. See #15 as an example. If #11 is still open, add the note about that, like #15.
