### ISSUE TITLE
How to write files

### ISSUE THREAD

**Issue by CWSpear** [cohesivelabs/filesystem#5]
We have `write`, (error of file exists), `update` (error of file does not exist) and `put` (write if not exists, otherwise update).

I think those can be handy and helpful. I'm not sold on the name and as related to #2, they don't have to all be implemented at the adapter level. If the adapter has `has` and `put`, the top level can handle the rest. However, we currently have `write` in the adapter interface... Which is confusing.

**Comment by jmartin84** [comment]
hmm, I mean I know that if I'm looking at an interface for file management I'd expect to see a method named write before a method named put. I guess it would make more sense though if we made the method name changes (ie write -> create)

**Comment by CWSpear** [comment]
Looks like we agreed on better naming in #7
