### ISSUE TITLE
API method names

### ISSUE THREAD

**Issue by CWSpear** [cohesivelabs/filesystem#7]
I am unsure on some API names:

`has` could be renamed `exists`

What about this proposed change:

Current -> Proposed
`write` -> `create`
`update` -> `update`
`put` -> `write`

And then the adapter only needs to implement `write`.

What about renaming `rename` to `move`?

**Comment by CWSpear** [comment]
I don't like `listContents`. I can't think of anything better: `scandir`, `scanDirectory`, `listDirectory`, `directoryContents`...

I also don't know if I like `metadata` over `getMetadata`... I think I do, but we have some getters and setters (like visibility), so maybe it should stat for consistency?

**Comment by jmartin84** [comment]
> has could be renamed exists
write -> create
update -> update
put -> write
What about renaming rename to move?

Love it

> I don't like listContents. I can't think of anything better: scandir, scanDirectory, listDirectory, directoryContents

I'm not in love with any of that, but I do think listContents is the lesser evil

> I also don't know if I like metadata over getMetadata... I think I do, but we have some getters and setters (like visibility), so maybe it should stat for consistency?

getter for consistency

**Comment by CWSpear** [comment]
What about `rename` vs `move`?

How about `listDirectoryContents` or `listDirContents`?

**Comment by CWSpear** [comment]
Also, what about `has` -> `exists`?

**Comment by dylan-surge** [comment]
rename, move -> relocate ?

**Comment by dylan-surge** [comment]
has = exists

**Comment by CWSpear** [comment]
re: has = exists

But not in word form and usage. "Does this file has?"

In fact, with it returning a boolean, it puts you in the mindset of a question, and I can't even think of how to phrase this as a question with `has`? "Does has file?"

**Comment by jmartin84** [comment]
@CWSpear 

write -> create
update -> update
put -> write
rename -> move
has -> exists

we good here?

**Comment by CWSpear** [comment]
I think so. Hope there isn't something we're not thinking of, haha
